name: labelling_transformer_deploy

on:
  push:
    branches:
      - "master"
    paths:
      - "workflows/transformers/labelling_transformer/**"
      - ".github/workflows/labelling_transformer_deploy.yml"

permissions:
  contents: read

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
          ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY_LABELLING_TRANSFORMER }}
          BUCKET_NAME: ${{ secrets.BUCKET_NAME }}
          PREPROCESSED_DATA_PATH_PREFIX: ${{ secrets.PREPROCESSED_DATA_PATH_PREFIX }}
          TOP_STOCKS_PRICES_EXTRACTED_PREFIX: ${{ secrets.TOP_STOCKS_PRICES_EXTRACTED_PREFIX }}
          LABELLED_DATA_DESTINATION_PREFIX: ${{ secrets.LABELLED_DATA_DESTINATION_PREFIX }}
        run: |
          # Change to the labelling_transformer directory.
          # Build a docker container and
          # push it to ECR so that it can
          # be deployed to lamba-function.
          cd workflows/transformers/labelling_transformer
          docker buildx build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG \
          --build-context piplock=../../../ \
          --build-arg PREPROCESSED_DATA_PATH_PREFIX=$PREPROCESSED_DATA_PATH_PREFIX \
          --build-arg TOP_STOCKS_PRICES_EXTRACTED_PREFIX=$TOP_STOCKS_PRICES_EXTRACTED_PREFIX \
          --build-arg LABELLED_DATA_DESTINATION_PREFIX=$LABELLED_DATA_DESTINATION_PREFIX \
          --build-arg BUCKET_NAME=$BUCKET_NAME \
          --output type=docker .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          echo "image=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT
