name: top_stock_data_extractor_deploy

on:
  push:
    branches:
      - "dev"
    paths:
      - "workflows/extractors/top_stock_data_extractor/**"

permissions:
  contents: read

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Change directory to top_stock_data_extractor
        run: cd workflows/extractors/top_stock_data_extractor

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
          ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY_TOP_STOCK_DATA_EXTRACTOR }}
          FINHUB_API_KEY: ${{ secrets.FINHUB_API_KEY }}
          BUCKET_NAME: ${{ secrets.BUCKET_NAME }}
        run: |
          # Build a docker container and
          # push it to ECR so that it can
          # be deployed to lzmba-function.
          docker buildx build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG \
          --build-context piplock=../../../ \
          --build-arg FINHUB_API_KEY=$FINHUB_API_KEY \
          --build-arg BUCKET_NAME=$BUCKET_NAME .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          echo "image=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT
